# this file is now only used for the pipeline to build and push, not to run.
# so nothing but these lines are needed.

version: '3.7'

services:

  web:
    build:
      context: NotesService
      dockerfile: api.Dockerfile
    image: ${IMAGENAMEPREFIX}2002-notes-api:${TAG}

  data:
    build:
      context: NotesService
      dockerfile: db.Dockerfile
    image: ${IMAGENAMEPREFIX}2002-notes-db:${TAG}
