version: '3.7'

services:

  # pipeline will push the 'web' service
  web:
    build: .
    image: nicholasescalona/2002-notes-api:1.0
    depends_on:
      - data
    ports:
      - 80:80
    networks:
      - default
    environment:
      DatabaseConnection: NotesDbPostgreSql
      ConnectionStrings__NotesDbPostgreSql: Host=data;Database=NotesDb;Username=postgres;Password=Pass@word
      CorsOrigins__0: https://2002-ng-notes-client.azurewebsites.net

  data:
    image: postgres:12.0
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: Pass@word

networks:
  default:
