version: '3.7'

services:

  web:
    build: NotesService
    image: nicholasescalona/2002-notes-api:1.0
    depends_on:
      - data
    ports:
      - 80:80
    networks:
      - default
    environment:
      DatabaseConnection: NotesDbPostgreSqlDockerCompose
      ConnectionStrings__NotesDbPostgreSqlDockerCompose: Host=data;Database=NotesDb;Username=postgres;Password=Pass@word
      EnsureDatabaseCreated: 'true'
      CorsOrigins__0: http://localhost:4200
      CorsOrigins__1: http://192.168.99.100:4200
      CorsOrigins__2: https://2002-ng-notes-client.azurewebsites.net
      UseHttpsRedirection: 'false'

  data:
    image: postgres:12.0
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: Pass@word

networks:
  default:
