# this file is now only used for the pipeline to build and push, not to run.
# so nothing but these lines are needed.

version: '3.7'

services:

  web:
    build: NotesService
    image: nicholasescalona/2002-notes-api:1.0
